//! llama.cpp's built-in tokenizer, reached through `llama_tokenize`.
//!
//! This is the tokenizer that actually runs in front of every local LLM served
//! by llama.cpp / Ollama / LM Studio, which makes it one of the few engines
//! here whose throughput is felt by end users rather than by training
//! pipelines. It is also the only one in the matrix that is a re-implementation
//! rather than a port: llama.cpp does not read `tokenizer.json`, it reads a
//! vocabulary out of a GGUF and applies a pre-tokenizer regex chosen by name
//! (`tokenizer.ggml.pre`) from a table compiled into the C++. Whether that
//! reconstruction agrees with the reference is exactly the interesting
//! question, and the harness's `verified` column answers it per cell.
//!
//! # The C API used
//!
//! ```c
//! struct llama_model* llama_model_load_from_file(const char*, struct llama_model_params);
//! const struct llama_vocab* llama_model_get_vocab(const struct llama_model*);
//! int32_t llama_tokenize(const struct llama_vocab* vocab,
//!                        const char* text, int32_t text_len,
//!                        llama_token* tokens, int32_t n_tokens_max,
//!                        bool add_special, bool parse_special);
//! ```
//!
//! `add_special = false` matches the reference's `add_special_tokens = false`:
//! no BOS/EOS, so the two id streams are comparable. `parse_special = false`
//! matches it too — the reference is asked for the plain-text reading of the
//! corpus, and letting llama.cpp recognise `<|endoftext|>` inside a document
//! would be a different question asked of a different tokenizer.
//!
//! # Why it needs `model.gguf` and refuses to run without one
//!
//! llama.cpp reads its vocabulary from the model file, so a cell only exists if
//! `data/models/<name>/model.gguf` does. That file is generated by
//! `engines/llamacpp/scripts/make_gguf.py`, which builds it **from this
//! model's own `data/models/<name>/tokenizer.json`** — not from an upstream
//! GGUF download. The distinction is the whole point: grabbing, say,
//! `Meta-Llama-3-8B.Q4.gguf` off the Hub would give a fast, plausible,
//! verified-looking row measuring a vocabulary that no other engine in the
//! matrix was given. When the GGUF is missing this engine says so and produces
//! nothing.
//!
//! # Cost model
//!
//! `llama_tokenize` writes into a caller-provided buffer and returns the count,
//! which suits the harness contract exactly: the buffer is sized once per
//! adapter and reused, so a steady-state encode allocates nothing. What is
//! *not* elided is the `i32 -> u32` copy into `out`: llama.cpp's ids are signed
//! and `Ids` is unsigned, and per the core fairness rules a conversion the
//! public API forces stays inside the measurement.
//!
//! # Class
//!
//! [`Class::Cffi`]: a C ABI called in-process on the same clock as the native
//! Rust engines. The only thing between the timer and the C++ is one `extern
//! "C"` call — see `build.rs` for why the hot path is not wrapped in a shim.

// Only the stub needs these at the top level; the wired engine imports its own
// (larger) set inside the module below.
#[cfg(not(llamacpp))]
use tokbench_core::{Build, Engine, Model, Unsupported};

/// The llama.cpp release this was linked against, resolved by `build.rs` from
/// `pkg-config --modversion llama`, or `"absent"` when nothing was found.
const VERSION: &str = env!("TOKBENCH_LLAMACPP_VERSION");

// ---------------------------------------------------------------------------
// Wired: an llama.cpp was found at build time.
// ---------------------------------------------------------------------------

#[cfg(llamacpp)]
mod wired {
    use super::VERSION;
    use std::ffi::{c_char, c_int, CString};
    use std::path::Path;
    use tokbench_core::{Build, Class, Engine, Ids, Info, Model, Unsupported};

    /// Opaque C types. Never dereferenced on this side — only handed back to
    /// llama.cpp — so an empty enum is the right representation: it cannot be
    /// constructed, and a `*mut` to it cannot be accidentally read.
    #[repr(C)]
    pub struct LlamaModel {
        _private: [u8; 0],
    }
    #[repr(C)]
    pub struct LlamaVocab {
        _private: [u8; 0],
    }

    unsafe extern "C" {
        // From src/shim.c: these are the calls that pass `llama_model_params`
        // by value, so they are laid out by the C compiler, not by us.
        fn tokbench_llama_load_vocab(path: *const c_char) -> *mut LlamaModel;
        fn tokbench_llama_silence();

        // Straight from llama.h. Pointers and scalars only, so declaring them
        // here is ABI-safe and keeps the hot call direct.
        fn llama_model_get_vocab(model: *const LlamaModel) -> *const LlamaVocab;
        fn llama_model_free(model: *mut LlamaModel);
        fn llama_tokenize(
            vocab: *const LlamaVocab,
            text: *const c_char,
            text_len: c_int,
            tokens: *mut i32,
            n_tokens_max: c_int,
            add_special: bool,
            parse_special: bool,
        ) -> c_int;
    }

    pub struct Adapter {
        model: *mut LlamaModel,
        /// Borrowed from `model` and valid for as long as it lives. Cached
        /// because `llama_model_get_vocab` on the hot path would be a second
        /// FFI call per encode for a value that never changes.
        vocab: *const LlamaVocab,
        /// The output buffer `llama_tokenize` fills. Grown to fit the largest
        /// document seen and then reused, which is what the C API is designed
        /// for and what a real caller does.
        scratch: Vec<i32>,
    }

    /// The harness builds one `Adapter` per thread (see `measure_scaling`) and
    /// moves it onto that thread. Nothing here is shared between threads: each
    /// instance owns its own `llama_model`, and `llama_tokenize` is documented
    /// upstream as thread-safe and takes `const llama_vocab *`. Note this is
    /// `Send` only — deliberately not `Sync`, because two threads sharing one
    /// instance would also share `scratch`.
    unsafe impl Send for Adapter {}

    impl Drop for Adapter {
        fn drop(&mut self) {
            // Matters for the memory column: the scaling sweep builds and drops
            // one model per thread per thread-count, and a leaked vocabulary
            // would be charged to whichever engine ran next.
            unsafe { llama_model_free(self.model) };
        }
    }

    impl Build for Adapter {
        fn build(model: &Model) -> Result<Box<dyn Engine>, Unsupported> {
            let Some(path) = model.artifact("model.gguf") else {
                return Err(Unsupported(format!(
                    "no model.gguf (llama.cpp reads its vocabulary from a GGUF, \
                     not tokenizer.json); generate one from this model's own \
                     tokenizer.json with `python engines/llamacpp/scripts/make_gguf.py {}`",
                    model.name
                )));
            };
            let c_path = cstring(&path)?;

            // Before the first load, or llama.cpp narrates ~80 lines of hparams
            // per model into the middle of the driver's output.
            unsafe { tokbench_llama_silence() };

            // SAFETY: `c_path` is a NUL-terminated path that exists; the shim
            // returns either a model we now own or null.
            let handle = unsafe { tokbench_llama_load_vocab(c_path.as_ptr()) };
            if handle.is_null() {
                return Err(Unsupported(format!(
                    "llama.cpp could not load {} (unsupported tokenizer type, or \
                     a GGUF it does not recognise)",
                    path.display()
                )));
            }

            // SAFETY: `handle` is a live model from the call above.
            let vocab = unsafe { llama_model_get_vocab(handle) };
            if vocab.is_null() {
                unsafe { llama_model_free(handle) };
                return Err(Unsupported(format!(
                    "{} carries no vocabulary",
                    path.display()
                )));
            }

            Ok(Box::new(Adapter {
                model: handle,
                vocab,
                scratch: Vec::new(),
            }))
        }
    }

    impl Engine for Adapter {
        fn info(&self) -> Info {
            Info {
                name: "llamacpp",
                version: VERSION,
                lang: "c++",
                class: Class::Cffi,
                url: "https://github.com/ggml-org/llama.cpp",
                also_computes: "",
                internally_parallel: false,
            }
        }

        fn encode(&mut self, text: &str, out: &mut Ids) {
            // Capacity, not a guess: every token consumes at least one input
            // byte, so a document can never produce more than `len` ids. The
            // `+ 1` covers the SentencePiece dummy prefix, which is the one
            // token that comes from nowhere in the input. Sized on the first
            // document and then reused for the rest of the corpus.
            let needed = text.len() + 1;
            if self.scratch.len() < needed {
                self.scratch.resize(needed, 0);
            }

            // SAFETY: `vocab` is alive for as long as `self`; `text` is valid
            // UTF-8 of the length passed (llama.cpp does not require NUL
            // termination, it takes an explicit length); `scratch` has room for
            // `scratch.len()` ids.
            let mut n = unsafe {
                llama_tokenize(
                    self.vocab,
                    text.as_ptr() as *const c_char,
                    text.len() as c_int,
                    self.scratch.as_mut_ptr(),
                    self.scratch.len() as c_int,
                    false, // add_special: no BOS/EOS, matching the reference
                    false, // parse_special: read the corpus as plain text
                )
            };

            if n < 0 {
                // Documented contract: a negative return is minus the number of
                // ids that would have been produced. Reaching this would mean
                // the bound above was wrong, but retrying costs nothing on a
                // path that never runs, and silently truncating a document
                // would corrupt the id hash the whole comparison rests on.
                let Ok(required) = usize::try_from(-(n as i64)) else {
                    return; // INT32_MIN: llama.cpp's own overflow signal.
                };
                self.scratch.resize(required, 0);
                n = unsafe {
                    llama_tokenize(
                        self.vocab,
                        text.as_ptr() as *const c_char,
                        text.len() as c_int,
                        self.scratch.as_mut_ptr(),
                        self.scratch.len() as c_int,
                        false,
                        false,
                    )
                };
                if n < 0 {
                    return;
                }
            }

            out.extend(self.scratch[..n as usize].iter().map(|&id| id as u32));
        }
    }

    /// Paths are bytes on Unix and llama.cpp takes `const char*`, so the only
    /// failure is an embedded NUL — which cannot come from a real file.
    fn cstring(path: &Path) -> Result<CString, Unsupported> {
        CString::new(path.to_string_lossy().into_owned())
            .map_err(|_| Unsupported("model path contains a NUL byte".into()))
    }
}

#[cfg(llamacpp)]
pub use wired::Adapter;

// ---------------------------------------------------------------------------
// Not wired: no llama.cpp on this machine.
// ---------------------------------------------------------------------------

/// The stub half of the crate. It exists so that `cargo check --workspace` and
/// `cargo build --features llamacpp` both succeed on a machine that has never
/// heard of llama.cpp: the cell is then reported as `Unsupported` with the
/// command that would fix it, which is the honest answer and, per the core
/// docs, better than a blank.
#[cfg(not(llamacpp))]
pub struct Adapter;

#[cfg(not(llamacpp))]
impl Build for Adapter {
    fn build(_model: &Model) -> Result<Box<dyn Engine>, Unsupported> {
        let _ = VERSION;
        Err(Unsupported(
            "llama.cpp not found at build time: install it (`brew install \
             llama.cpp`, or a distro package providing llama.h + libllama) or \
             point LLAMA_CPP_DIR at a built checkout, then rebuild"
                .into(),
        ))
    }
}
